### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by AliAlmasi** [sepsoh/crawat#2]
I wanted to see how this works; I've got the files on my localhost web server and it seems like something's wrong.  
Would you please work on the 'wiki' section of your repo? Thanks.

**Comment by sepsoh** [comment]
Hi Ali, If Telegram is limited for you in your country, you should use vpn on localhost.  Using this script on the localhost has no meaning except for testing it, it must be placed on the server.  I will make a complete documentation for this script in the near future.
